# Site settings
title: AIoTC Blog
SEOTitle: debugger999的博客 | debugger999
header-img: img/post-bg-desk.jpg
email: debugger999@163.com
description: "debugger999的博客"
keyword: "AIoTCloud"
url: "http://debugger999.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     debugger999
#zhihu_username:     debugger999
#github_username:    debugger999
#twitter_username:  debugger999
#facebook_username:  debugger999



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: debugger999
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Gitalk
gitalk:
  enable: true
  clientID: 4525305852c0d78ad92b
  clientSecret: dd3b857dd65b5d07a2902420ae4a99a8d0d55777
  repo: debugger999.github.io
  owner: debugger999
  admin: debugger999
  distractionFreeMode: true


# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: debugger999.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "现状只是积累，靠耐心活在未来"
sidebar-avatar: /img/aboutme.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "GitHub·debugger999",
        href: "http://debugger999.github.io"
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]
